services:
  login:
    container_name: login-container
    build: ./node-login
    ports:
      - 80:8080
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mysql
    restart: on-failure
    depends_on:
    - mysqlz
  mysql:
    image: mysql:5.7
    container_name: database-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql-config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-config/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf


 

            